name: API Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run API Tests
        run: pytest --alluredir=reports

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports
