name: API Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install allure-pytest
        run: pip install allure-pytest

      - name: Check installed packages
        run: pip list | grep allure

      - name: Run API Tests
        run: pytest --alluredir=reports

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.6
        with:
            allure_results: allure-results
            allure_report: allure-report
            gh_pages: gh-pages

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports
